# database properties
#server.servlet.session.cookie.same-site=Strict
#app.jdbc.driverClassName=com.mysql.jdbc.Driver
#app.jdbc.url=jdbc:mysql://49.50.64.225:3306/
#app.jdbc.username=root
#app.jdbc.password=VR#3D##DD@2

#hibernate properties
hibernate.config=/WEB-INF/hibernate.cfg.xml


################### JDBC Configuration ##########################
jdbc.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#live connection
#Live DB Connection

##uat connection
#jdbc.url=jdbc:sqlserver://49.50.79.104;databaseName=XMWJCI
#jdbc.username=sa
#jdbc.password=India@12310
###uat connection
#jdbc.url=jdbc:sqlserver://49.50.79.104;databaseName=Live-XMWJCI
#jdbc.username=sa
#jdbc.password=India@12310


#jdbc.url=jdbc:sqlserver://49.50.97.20;databaseName=PNB_LIVE

uat DB connection
jdbc.url=jdbc:sqlserver://49.50.79.104;databaseName=XMWJCI
jdbc.username=sa
jdbc.password=India@12310

#Live DB Connection
#jdbc.url=jdbc:sqlserver://49.50.79.54:4352;databaseName=XMWJCI
#jdbc.username=sa
#jdbc.password=G45&)`!63jdd


>

#Live DB Connection
<<<<<<< HEAD
#jdbc.url=jdbc:sqlserver://49.50.79.54:4352;databaseName=XMWJCI
#jdbc.username=sa
#jdbc.password=G45&)`!63jdd
=======
#jdbc.url=jdbc:sqlserver://49.50.79.54:4352;databaseName=XMWJCI
#jdbc.username=sa
#jdbc.password=G45&)`!63jdd
#>>>>>>> 8d18cac28d2d316bbcf7768a43d8d15bcda137d5
####################### Live Credentials########################
#jdbc.url=jdbc:sqlserver://49.50.79.54:4352;databaseName=XMWJCI
#jdbc.username=sa
#jdbc.password=G45&)`!63jdd
##

################### Hibernate Configuration ##########################
hibernate.dialect=org.hibernate.dialect.SQLServerDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update
hibernate.generate_statistics=false


#CSRF DISABLE
security.enable-csrf=false

#upload.farmer = C:\\cmsjcii\\jci-cms\\jciadmin\\JciUploadImages\\farmerReg
upload.farmer = E:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\FarmerRegistration\

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=INFO
logging.file.name=E:\log\app.log
#local folder link-----               
#upload.tallyexcel = C:\\Demo Data\\
#UAT folder link-----
upload.tallyexcel =E:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\TallySlipPayment\

###localfolder path
####
#upload.requestLetter = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\RequestLetters
#upload.contractLetter = C:\\\\Users\\\\pradeep.rathor\\\\Desktop\\\\JCIStuff\\\\Contracts
#upload.authorizedContracts = C:\\\\Users\\\\pradeep.rathor\\\\Desktop\\\\JCIStuff\\\\AuthorizedContract
#upload.contractLetterJava = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\Contracts
#upload.creditNoteDetails =  C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\CreditNotes
#upload.creditNoteSettlement =  C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\CreditNoteSettlemt
#upload.letterHeadPath =  C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\fullLetterHead.png
#upload.SignaturePdf =  C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\signature2.png
#upload.creditNoteJRXML = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\creditNote.jrxml
#upload.creditNoteSettledJRXML = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\creditNoteClaim.jrxml
#upload.PaymentRealizationDisDetails = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\PaymentRealization_DisDetails
#upload.weightmentDoc = http:\\49.50.118.112:8080\\WeightSlipment
#upload.dispatchDoc = http:\\49.50.118.112:8080\\DispatchDetail
#upload.bosDoc = http:\\49.50.118.112:8080\\billofsupply
###vishwdeep
#upload.Confirmationsettlement = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\Claim\\
#upload.ConfirmationsettlementFA = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\Claim\\
#upload.HoDiDoc = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\hoDispatch\\
#upload.hodispatch = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\hodispatch.jrxml
#upload.DemandDoc = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\DemandNote.jrxml
#upload.DemandNoteSave = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\DemandNoteDoc\\
#*************************************************************************************
#mansi
#upload.millAcceptDownolad = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\AuthorizedContract
#upload.claimSettlementReportDownload =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\claimSettlementReport\\
#upload.claimsetlmentJRXMLpath = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\claimReport.jrxml
#upload.GenrationofbillDownload = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\billofsupply
#upload.EntryTdsSupportingDocument = C:\Users\Mansi.Gupta\Documents\New folder (2)
#upload.EntryOfTdsDownolad= C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\TdsDocument
#upload.BOENONLCJasperReport = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\BOENONLC.jrxml
#upload.BOENONLCDownload = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\BOENONLCDownload
#upload.TopSheetNONLCJasperReport = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\TopSheetReportNONLC.jrxml
#upload.TopSheetNONLCDownload =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\TopSheetNONLCDownload
#upload.cndnuploadxl = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\CNDNExcelSave
#upload.cndndownloadxl =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\CNDNExcelSave
#upload.PaymentRealizationDisDetails =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\PaymentRealization_DisDetails
#upload.cbipaymentMandateJRXML= C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\CBI_PAYMENT_MANDATE.jrxml
#upload.cbiPaymentMandateCNDN=C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\CBIPaymentMandate
##kailash
#upload.PaymentDocument =  C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\paymentDocument
#upload.Genrationofbill = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\billofsupply
#upload.billofsupplyJrxml = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\billofsupply.jrxml
#upload.BOSReports = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\billOfExchange
#upload.TopSheetPathJasper =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\topsheet.jrxml
#upload.BankDraftpathJsaper =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\BOEDOC.jrxml
#upload.BillofExchagePathJasper = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\billofexchange.jrxml
#upload.fcreport = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\fcreport.jrxml
#upload.fcDownoad1 = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\fcreport
#upload.fcDownoad = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\fcreport
#upload.baseIp =http://49.50.118.112:8080



##UAT Path
#upload.requestLetter = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\RequestLetters
#upload.contractLetter = C:\\\\Program Files\\\\Apache Software Foundation\\\\Tomcat 8.5\\\\webapps\\\\JCIStuff\\\\Contracts
#upload.authorizedContracts = C:\\\\Program Files\\\\Apache Software Foundation\\\\Tomcat 8.5\\\\webapps\\\\JCIStuff\\\\AuthorizedContract
#upload.contractLetterJava = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Contracts
#upload.creditNoteDetails =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CreditNotes
#upload.creditNoteSettlement =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CreditNoteSettlemt
#upload.letterHeadPath =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\fullLetterHead.png
#upload.SignaturePdf =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\signature2.png
#upload.creditNoteJRXML = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\creditNote.jrxml
#upload.creditNoteSettledJRXML = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\creditNoteClaim.jrxml
#upload.PaymentRealizationDisDetails = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\PaymentRealization_DisDetails
#upload.weightmentDoc = http:\\49.50.118.112:8080\\WeightSlipment
#upload.dispatchDoc = http:\\49.50.118.112:8080\\DispatchDetail
#upload.bosDoc = http:\\49.50.118.112:8080\\billofsupply
####vishwdeep
#upload.Confirmationsettlement = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Claim\\
#upload.ConfirmationsettlementFA = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Claim\\
#upload.HoDiDoc = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\hoDispatch\\
#upload.hodispatch =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\hodispatch.jrxml
#upload.DemandDoc = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\DemandNote.jrxml
#upload.DemandNoteSave =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\DemandNoteDoc\\
##
###*************************************************************************************
##
####mansi
#upload.millAcceptDownolad =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\AuthorizedContract
#upload.claimSettlementReportDownload =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\claimSettlementReport\\
#upload.claimsetlmentJRXMLpath = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\claimReport.jrxml
#upload.GenrationofbillDownload = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofsupply
#upload.EntryTdsSupportingDocument = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TdsDocument
#upload.EntryOfTdsDownolad= C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TdsDocument
#upload.BOENONLCJasperReport = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\BOENONLC.jrxml
#upload.BOENONLCDownload = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\BOENONLCDownload
#upload.TopSheetNONLCJasperReport =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TopSheetReportNONLC.jrxml
#upload.TopSheetNONLCDownload =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TopSheetNONLCDownload
#upload.cndnuploadxl = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CNDNExcelSave
#upload.cndndownloadxl =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CNDNExcelSave
#upload.PaymentRealizationDisDetails =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\PaymentRealization_DisDetails
#upload.cbipaymentMandateJRXML= C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CBI_PAYMENT_MANDATE.jrxml
#upload.cbiPaymentMandateCNDN=C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CBIPaymentMandate
###kailash
#upload.PaymentDocument =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\paymentDocument
#upload.Genrationofbill =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofsupply
#upload.billofsupplyJrxml = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofsupply.jrxml
#upload.BOSReports = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billOfExchange
#upload.TopSheetPathJasper =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\topsheet.jrxml
#upload.BankDraftpathJsaper =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\BOEDOC.jrxml
#upload.BillofExchagePathJasper = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofexchange.jrxml
#upload.fcreport = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\fcreport.jrxml
#upload.fcDownoad1 =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\fcreport
#upload.fcDownoad =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\fcreport
#upload.baseIp =http://49.50.118.112:8080
#





##Live Path
#Pradeep
upload.requestLetter = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\RequestLetters
upload.contractLetter = C:\\\\Users\\\\Administrator\\\\Downloads\\\\apache-tomcat-8.5.73-windows-x64\\\\apache-tomcat-8.5.73\\\\webapps\\\\JCIStuff\\\\Contracts
upload.authorizedContracts = C:\\\\Users\\\\Administrator\\\\Downloads\\\\apache-tomcat-8.5.73-windows-x64\\\\apache-tomcat-8.5.73\\\\webapps\\\\JCIStuff\\\\AuthorizedContract
upload.contractLetterJava = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\Contracts
upload.creditNoteDetails = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\CreditNotes
upload.creditNoteSettlement = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\CreditNoteSettlemt
upload.letterHeadPath = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\fullLetterHead.png
upload.SignaturePdf = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\signature2.png
upload.creditNoteJRXML = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\creditNote.jrxml
upload.creditNoteSettledJRXML = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\creditNoteClaim.jrxml
upload.PaymentRealizationDisDetails = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\PaymentRealization_DisDetails
upload.weightmentDoc = http:\\49.50.118.125:8080\\WeightSlipment
upload.dispatchDoc = http:\\49.50.118.125:8080\\DispatchDetail
upload.bosDoc = http:\\49.50.118.125:8080\\billofsupply
Vishwdeep
upload.Confirmationsettlement = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\Claim\\
upload.ConfirmationsettlementFA = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\Claim\\
upload.HoDiDoc = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\hoDispatch\\
upload.hodispatch = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\hodispatch.jrxml
upload.DemandDoc = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\DemandNote.jrxml
upload.DemandNoteSave = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\DemandNoteDoc\\
Mansi
upload.millAcceptDownolad = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\AuthorizedContract
upload.claimSettlementReportDownload = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\claimSettlementReport\\
upload.claimsetlmentJRXMLpath = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\claimReport.jrxml
upload.GenrationofbillDownload = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\billofsupply
upload.EntryTdsSupportingDocument = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\TdsDocument
upload.EntryOfTdsDownolad = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\TdsDocument
upload.BOENONLCJasperReport = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\BOENONLC.jrxml
upload.BOENONLCDownload = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\BOENONLCDownload
upload.TopSheetNONLCJasperReport = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\TopSheetReportNONLC.jrxml
upload.TopSheetNONLCDownload = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\TopSheetNONLCDownload
upload.cndnuploadxl = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\CNDNExcelSave
upload.cndndownloadxl = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\CNDNExcelSave
upload.PaymentDocument = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\paymentDocument
upload.cbipaymentMandateJRXML= C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\CBI_PAYMENT_MANDATE.jrxml
upload.cbiPaymentMandateCNDN= C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\CBIPaymentMandate
kailash
upload.Genrationofbill = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\billofsupply
upload.billofsupplyJrxml = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\billofsupply.jrxml
upload.BOSReports = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\billOfExchange
upload.TopSheetPathJasper = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\topsheet.jrxml
upload.BankDraftpathJsaper = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\BOEDOC.jrxml
upload.BillofExchagePathJasper = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\billofexchange.jrxml
upload.fcreport = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73-windows-x64\\apache-tomcat-8.5.73\\webapps\\JCIStuff\\fcreport.jrxml
upload.fcDownoad1 = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73
upload.fcDownoad = C:\\Users\\Administrator\\Downloads\\apache-tomcat-8.5.73
upload.baseIp =http://49.50.118.125:8080



