# database properties
server.servlet.session.cookie.same-site=Strict
app.jdbc.driverClassName=com.mysql.jdbc.Driver
app.jdbc.url=jdbc:mysql://49.50.64.225:3306/
app.jdbc.username=root
app.jdbc.password=VR#3D##DD@2

#hibernate properties
hibernate.config=/WEB-INF/hibernate.cfg.xml


################### JDBC Configuration ##########################
jdbc.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#live connection
#Live DB Connection


#uat connection
jdbc.url=jdbc:sqlserver://49.50.79.104;databaseName=XMWJCI
jdbc.username=sa
jdbc.password=India@12310

####################### Live Credentials########################
#jdbc.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
##uat connection
#jdbc.url=jdbc:sqlserver://10.192.22.127;databaseName=pnb
#jdbc.username=sa
#jdbc.password=Pnboct2018#


################### Hibernate Configuration ##########################
hibernate.dialect=org.hibernate.dialect.SQLServerDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update
hibernate.generate_statistics=false


#CSRF DISABLE
security.enable-csrf=false

#upload.farmer = C:\\cmsjcii\\jci-cms\\jciadmin\\JciUploadImages\\farmerReg
upload.farmer = E:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\FarmerRegistration\

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=INFO
logging.file.name=E:\log\app.log
#local folder link-----               
#upload.tallyexcel = C:\\Demo Data\\
#UAT folder link-----
upload.tallyexcel =E:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\TallySlipPayment\


#******************** UAT FILE PATH *************************
##pradeep
#upload.requestLetter = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\RequestLetters
#upload.contractLetter = C:\\\\Program Files\\\\Apache Software Foundation\\\\Tomcat 8.5\\\\webapps\\\\JCIStuff\\\\Contracts
#upload.authorizedContracts = C:\\\\Program Files\\\\Apache Software Foundation\\\\Tomcat 8.5\\\\webapps\\\\JCIStuff\\\\AuthorizedContract
#upload.contractLetterJava = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Contracts
#upload.creditNoteJRXML =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\creditNote.jrxml
#upload.creditNoteDetails =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CreditNotes
#upload.PaymentRealizationDisDetails = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\PaymentRealization_DisDetails
#upload.letterHeadPath =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\fullLetterHead.png
#upload.creditNoteSettledJRXML =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\creditNoteClaim.jrxml
#upload.creditNoteSettlement =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CreditNoteSettlemt
#upload.SignaturePdf =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\signature2.png
#upload.weightmentDoc = http:\\49.50.118.112:8080\\WeightSlipment
#upload.dispatchDoc = http:\\49.50.118.112:8080\\DispatchDetail
#upload.bosDoc = http:\\49.50.118.112:8080\\billofsupply
###
####vishwdeep
#upload.Confirmationsettlement = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Claim\\
#upload.ConfirmationsettlementFA = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Claim\\
#upload.HoDiDoc = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\hoDispatch\\
#upload.hodispatch = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\hodispatch.jrxml
###
####mansi
#upload.millAcceptDownolad = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\AuthorizedContract
#upload.claimSettlementReportDownload = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\claimSettlementReport\\
#upload.claimsetlmentJRXMLpath = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\claimReport.jrxml
#upload.GenrationofbillDownload = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofsupply
#upload.EntryTdsSupportingDocument = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TdsDocument
#upload.EntryOfTdsDownolad= C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TdsDocument
#upload.BOENONLCJasperReport = C:\\Users\\Mansi.Gupta\\Documents\\mspcodemerge_1july\\JCI-CMS\\BOENONLC.jrxml
#upload.BOENONLCDownload = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\BOENONLCDownload
#upload.TopSheetNONLCJasperReport = C:\\Users\\Mansi.Gupta\\Documents\\mspcodemerge_1july\\JCI-CMS\\TopSheetReportNONLC.jrxml
#upload.TopSheetNONLCDownload = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\ TopSheetNONLCDownload
#upload.paymentDocumentDownload = C:\\Users\\Mansi.Gupta\\Documents\\paymentDocumentCashAgainstDispatchDocumentNonLc
#upload.cndnuploadxl = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CNDNExcelSave
#upload.cndndownloadxl =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CNDNExcelSave
#upload.PaymentRealizationDisDetails = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\PaymentRealization_DisDetails
#upload.ConsigneeDocDownloadForSettlementOfCNDN = C:\\Users\\Mansi.Gupta\\Documents\\CreditNoteDOc DownLoad

###
####kailash
#upload.PaymentDocument =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\documentimage
#upload.Genrationofbill = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofsupply
#upload.BOSReports = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billOfSupplyDocument
#upload.TopSheetPathJasper =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\topsheet.jrxml
#upload.BankDraftpathJsaper = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\BOEDOC.jrxml
#upload.BillofExchagePathJasper = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofexchange.jrxml
#upload.fcreport = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\fcreport.jrxml
##
##*************************************************************************************
###localfolder path
##
upload.requestLetter = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\RequestLetters
upload.contractLetter = C:\\\\Users\\\\pradeep.rathor\\\\Desktop\\\\JCIStuff\\\\Contracts
upload.authorizedContracts = C:\\\\Users\\\\pradeep.rathor\\\\Desktop\\\\JCIStuff\\\\AuthorizedContract
upload.contractLetterJava = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\Contracts
upload.creditNoteDetails =  C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\CreditNotes
upload.creditNoteSettlement =  C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\CreditNoteSettlemt
upload.letterHeadPath =  C:\\Users\\pradeep.rathor\\Desktop\\JCI-PHASE1\\JCI-CMS\\WebContent\\assets\\img\\fullLetterHead.png
upload.SignaturePdf =  C:\\Users\\pradeep.rathor\\Desktop\\JCI-PHASE1\\JCI-CMS\\WebContent\\assets\\img\\signature2.png
upload.creditNoteJRXML = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\creditNote.jrxml
upload.creditNoteSettledJRXML = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\creditNoteClaim.jrxml
upload.PaymentRealizationDisDetails = C:\\Users\\Mansi.Gupta\\Documents\\PaymentRealization_DisDetails
upload.weightmentDoc = http:\\49.50.118.112:8080\\WeightSlipment
upload.dispatchDoc = http:\\49.50.118.112:8080\\DispatchDetail
upload.bosDoc = http:\\49.50.118.112:8080\\billofsupply
###vishwdeep

upload.Confirmationsettlement = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\Claim\\
upload.ConfirmationsettlementFA = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\Claim\\
upload.HoDiDoc = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\hoDispatch\\
upload.hodispatch = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\hodispatch.jrxml
upload.DemandDoc = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\DemandNote.jrxml
upload.DemandNoteSave = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\DemandNoteDoc\\

#
##*************************************************************************************
#
##mansi
upload.millAcceptDownolad = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\AuthorizedContract
upload.claimSettlementReportDownload =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\claimSettlementReport\\
upload.claimsetlmentJRXMLpath = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\claimReport.jrxml
upload.GenrationofbillDownload = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\billofsupply
upload.EntryTdsSupportingDocument = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\TdsDocument
upload.EntryOfTdsDownolad= C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\TdsDocument
upload.BOENONLCJasperReport = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\BOENONLC.jrxml
upload.BOENONLCDownload = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\BOENONLCDownload
upload.TopSheetNONLCJasperReport = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\TopSheetReportNONLC.jrxml
upload.TopSheetNONLCDownload =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\TopSheetNONLCDownload
upload.cndnuploadxl = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\CNDNExcelSave
upload.cndndownloadxl =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\CNDNExcelSave
upload.PaymentRealizationDisDetails =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\PaymentRealization_DisDetails


##kailash
upload.PaymentDocument =  C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\paymentDocument
upload.Genrationofbill = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\billofsupply
upload.billofsupplyJrxml = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\billofsupply.jrxml
upload.BOSReports = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\billOfExchange
upload.TopSheetPathJasper =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\topsheet.jrxml
upload.BankDraftpathJsaper =C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\BOEDOC.jrxml
upload.BillofExchagePathJasper = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\billofexchange.jrxml
upload.fcreport = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\fcreport.jrxml
upload.fcDownoad1 = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\fcreport
upload.fcDownoad = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\fcreport


##UAT path
##
#upload.requestLetter = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\RequestLetters
#upload.contractLetter = C:\\\\Program Files\\\\Apache Software Foundation\\\\Tomcat 8.5\\\\webapps\\\\JCIStuff\\\\Contracts
#upload.authorizedContracts = C:\\\\Program Files\\\\Apache Software Foundation\\\\Tomcat 8.5\\\\webapps\\\\JCIStuff\\\\AuthorizedContract
#upload.contractLetterJava = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Contracts
#upload.creditNoteDetails =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CreditNotes
#upload.creditNoteSettlement =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CreditNoteSettlemt
#upload.letterHeadPath =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\fullLetterHead.png
#upload.SignaturePdf =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\signature2.png
#upload.creditNoteJRXML = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\creditNote.jrxml
#upload.creditNoteSettledJRXML = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\creditNoteClaim.jrxml
#upload.PaymentRealizationDisDetails = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\PaymentRealization_DisDetails
#upload.weightmentDoc = http:\\49.50.118.112:8080\\WeightSlipment
#upload.dispatchDoc = http:\\49.50.118.112:8080\\DispatchDetail
#upload.bosDoc = http:\\49.50.118.112:8080\\billofsupply
####vishwdeep
#
#upload.Confirmationsettlement = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Claim\\
#upload.ConfirmationsettlementFA = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Claim\\
#upload.HoDiDoc = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\hoDispatch\\
#upload.hodispatch =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\hodispatch.jrxml
#upload.DemandDoc = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\DemandNote.jrxml
#upload.DemandNoteSave =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\DemandNoteDoc\\
#
##
###*************************************************************************************
##
###mansi
#upload.millAcceptDownolad =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\AuthorizedContract
#upload.claimSettlementReportDownload =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\claimSettlementReport\\
#upload.claimsetlmentJRXMLpath = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\claimReport.jrxml
#upload.GenrationofbillDownload = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofsupply
#upload.EntryTdsSupportingDocument = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TdsDocument
#upload.EntryOfTdsDownolad= C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TdsDocument
#upload.BOENONLCJasperReport = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\BOENONLC.jrxml
#upload.BOENONLCDownload = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\BOENONLCDownload
#upload.TopSheetNONLCJasperReport =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TopSheetReportNONLC.jrxml
#upload.TopSheetNONLCDownload =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TopSheetNONLCDownload
#upload.cndnuploadxl = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CNDNExcelSave
#upload.cndndownloadxl =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CNDNExcelSave
#upload.PaymentRealizationDisDetails =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\PaymentRealization_DisDetails
#
###kailash
#upload.PaymentDocument =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\paymentDocument
#upload.Genrationofbill =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofsupply
#upload.billofsupplyJrxml = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofsupply.jrxml
#upload.BOSReports = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billOfExchange
#upload.TopSheetPathJasper =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\topsheet.jrxml
#upload.BankDraftpathJsaper =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\BOEDOC.jrxml
#upload.BillofExchagePathJasper = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofexchange.jrxml
#upload.fcreport = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\fcreport.jrxml
#upload.fcDownoad1 =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\fcreport
#upload.fcDownoad =C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\fcreport




