# database properties
server.servlet.session.cookie.same-site=Strict
app.jdbc.driverClassName=com.mysql.jdbc.Driver
app.jdbc.url=jdbc:mysql://49.50.64.225:3306/
app.jdbc.username=root
app.jdbc.password=VR#3D##DD@2

#hibernate properties
hibernate.config=/WEB-INF/hibernate.cfg.xml
 

################### JDBC Configuration ##########################
jdbc.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#live connection
#Live DB Connection


#uat connection
jdbc.url=jdbc:sqlserver://49.50.79.104;databaseName=XMWJCI
jdbc.username=sa
jdbc.password=India@12310

####################### Live Credentials########################
#jdbc.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
##uat connection
#jdbc.url=jdbc:sqlserver://10.192.22.127;databaseName=pnb
#jdbc.username=sa
#jdbc.password=Pnboct2018#


################### Hibernate Configuration ##########################
hibernate.dialect=org.hibernate.dialect.SQLServerDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update
hibernate.generate_statistics=false


#CSRF DISABLE
security.enable-csrf=false

#upload.farmer = C:\\cmsjcii\\jci-cms\\jciadmin\\JciUploadImages\\farmerReg
upload.farmer = E:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\FarmerRegistration\

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=INFO
logging.file.name=E:\log\app.log
 #local folder link-----               
#upload.tallyexcel = C:\\Demo Data\\
#UAT folder link-----
upload.tallyexcel =E:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\TallySlipPayment\


upload.requestLetter = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\RequestLetters
upload.contractLetter = C:\\\\Program Files\\\\Apache Software Foundation\\\\Tomcat 8.5\\\\webapps\\\\JCIStuff\\\\Contracts
upload.authorizedContracts = C:\\\\Program Files\\\\Apache Software Foundation\\\\Tomcat 8.5\\\\webapps\\\\JCIStuff\\\\AuthorizedContract
upload.contractLetterJava = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Contracts
upload.creditNoteDetails =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\CreditNotes
upload.PaymentRealizationDisDetails = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\PaymentRealization_DisDetails
##external files for the pdf generation
upload.letterHeadPath =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\fullLetterHead.png
upload.SignaturePdf =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\signature2.png
upload.creditNoteJRXML =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\creditNote.jrxml
upload.weightmentDoc = http:\\49.50.118.112:8080\\WeightSlipment
upload.dispatchDoc = http:\\49.50.118.112:8080\\DispatchDetail



upload.PaymentDocument =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\documentimage
upload.Genrationofbill = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\billofsupply
#upload.Confirmationsettlement = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\documentimage

upload.Confirmationsettlement = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Claim\\
upload.ConfirmationsettlementFA = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Claim\\


#upload.FAofficialDocumentDownload=C:\\Users\\Mansi.Gupta\\Downloads\\new.jpg
#upload.MillDocumentDownload=C:\\Users\\Mansi.Gupta\\Downloads\\new.jpg
#<<<<<<< HEAD
#upload.EntryTdsSupportingDocument = C:\Users\Mansi.Gupta\Downloads\mill accept
#upload.EntryOfTdsDownolad= C:\Users\Mansi.Gupta\Downloads\mill accept
#upload.OMOofficialDocumentDownload= C:\\Users\\Mansi.Gupta\\Downloads\\dummy.jpg
#upload.millAcceptDownolad = C:\\Users\\Mansi.Gupta\\Documents\\millAcceptFile
#

upload.OMOofficialDocumentDownload= C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\new.jpg
upload.EntryTdsSupportingDocument = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TdsDocument
upload.EntryOfTdsDownolad= C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\TdsDocument
upload.millAcceptDownolad = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Contracts


#localfolder path
 
#upload.requestLetter = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\RequestLetters
#upload.contractLetter = C:\\\\Users\\\\pradeep.rathor\\\\Desktop\\\\JCIStuff\\\\Contracts
#upload.authorizedContracts = C:\\\\Users\\\\pradeep.rathor\\\\Desktop\\\\JCIStuff\\\\AuthorizedContract
#upload.contractLetterJava = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\Contracts
#upload.creditNoteDetails =  C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\CreditNotes
#upload.letterHeadPath =  C:\\Users\\pradeep.rathor\\Desktop\\JCI-PHASE1\\JCI-CMS\\WebContent\\assets\\img\\fullLetterHead.png
#upload.SignaturePdf =  C:\\Users\\pradeep.rathor\\Desktop\\JCI-PHASE1\\JCI-CMS\\WebContent\\assets\\img\\signature2.png
#upload.creditNoteJRXML = C:\\Users\\pradeep.rathor\\Desktop\\creditNote.jrxml
#upload.PaymentRealizationDisDetails = C:\\Users\\pradeep.rathor\\Desktop\\JCIStuff\\PaymentRealization_DisDetails
#upload.weightmentDoc = http:\\49.50.118.112:8080\\WeightSlipment
#upload.dispatchDoc = http:\\49.50.118.112:8080\\DispatchDetail

#upload.PaymentDocument =  C:\\Users\\kailash.shah\\documentimage
#upload.Genrationofbill =  C:\\Users\\kailash.shah\\documentimage
##upload.Confirmationsettlement =  C:\\Users\\kailash.shah\\documentimage

#upload.Confirmationsettlement = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\documentimage\\
#=======
#upload.PaymentDocument =  C:\\Users\\kailash.shah\\documentimage
#upload.Genrationofbill =  C:\\Users\\kailash.shah\\documentimage
##upload.Confirmationsettlement =  C:\\Users\\kailash.shah\\documentimage
##
#upload.Confirmationsettlement =  C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\ClaimSettlement
#
#
#
#
#
#
#>>>>>>> 9869c8f2b0f625535aa568ef9941255e7b3aa99b


## document which we have to send to mill fa omo thier path will here
#upload.FAofficialDocumentDownload=C:\\Users\\Mansi.Gupta\\Downloads\\new.jpg
#upload.MillDocumentDownload=C:\\Users\\Mansi.Gupta\\Downloads\\new.jpg

#upload.EntryTdsSupportingDocument = C:\Users\Mansi.Gupta\Downloads\mill accept
#upload.EntryOfTdsDownolad= C:\Users\Mansi.Gupta\Downloads\mill accept
#upload.OMOofficialDocumentDownload= C:\\Users\\Mansi.Gupta\\Downloads\\dummy.jpg
#upload.millAcceptDownolad = C:\\Users\\Mansi.Gupta\\Documents\\millAcceptFile

#Local
#upload.Confirmationsettlement = C:\\Users\\pradeep.rathor\\Desktop\\Claim\\

#UAT
#upload.Confirmationsettlement = C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\webapps\\JCIStuff\\Claim\\


#Local
#upload.Confirmationsettlement =C:\\Users\\vishwdeep.singharia\\Desktop\\ClaimSettlement\\

#upload.ConfirmationsettlementFA =C:\\Users\\vishwdeep.singharia\\Desktop\\ClaimSettlement\\

